### ISSUE TITLE
Double PnP-PortalFooter-Links 

### ISSUE THREAD

**Issue by richov** [pnp/sp-starter-kit#388]
#335 ## Category
- [x] Question
- [x] Bug
- [ ] Enhancement

Hi All,
Not sure if this is a bug or a question so I have select both, I hope this is allowed.  

Q. Has anyone else had a double footer on their site? My pnp-footer is showing twice, one on top of the other. I have no idea how this has happened - Can anyone point me in the right direction to remove one of them, please?

#### Observed Behavior

Double PnP-PortalFooter showing across my site

#### Steps to Reproduce

Unknown

Thank in advanced
Rich

**Comment by eoverfield** [comment]
This is not the expected behavior. Did you install the starter kit twice? or a newer version over an older version? Is this double footer on the collaboration site and both team sites? How about other sites within your tenant?

Best method to remove, use PnP PowerShell and Get-PnPCustomAction to find the existing custom actions, then remove-pnpcustomaction to remove the additional extension.

**Comment by richov** [comment]
How do I safely remove this?

**Comment by bcameron1231** [comment]
@richov  As Eric mentioned, you can use PnP-PowerShell Get-PnPCustomAction and Remove-PnPCustomAction to remove it from your site.

`Get-PnPCustomAction -Scope Site` will give you all the custom actions. You can find the ID for the Portal Footer.

Use this ID to remove the Custom Action using `Remove-PnPCustomAction.`
