### ISSUE TITLE
Guidance for Using the Content Type Hub with the Starter Kit

### ISSUE THREAD

**Issue by pdemro** [pnp/sp-starter-kit#392]
## Category

- [x] Question

## Question

This is a re-post of a question posed to the PnP Provisioning team w/r/t provisioning sites & site schemas in the context of using a Content Type Hub in SharePoint Online.  Per the implementation of the content type hub there is a delay between when a site is created, and when the content types are available on the site.  This causes provisioning errors if a site template is using any elements from the content type hub for list/library schemas.

Guidance I have been able to find so far from Microsoft is that they are aware of the issue, but don't have plans to address it.  Workarounds have been proposed with some traction but have been rejected https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/15147111-allow-publishing-of-content-type-hub-content-types

https://github.com/pnp/PnP-Sites-Core/issues/2598

I am asking to open a discussion with experts on best practice guidance for working around this problem.

**Comment by bcameron1231** [comment]
Understandably, this is a pretty big deal for organizations that use the content type hub. As you mention, the content type hub syndication has seen some issues in SharePoint Online where content types aren't readily available when a new site is created. In fact, I've seen it take over a day before content types syndicate in large environments.

With that being said, I typically do not recommend using the Content Type Hub in SharePoint Online. Yes, it is nice to have a single place for content type updates, but it just isn't as reliable as it needs to be to use it in my opinion.  

Typically when I get asked this question, I recommend not using the Content Type Hub. I provisioning out Content Types individually for each site collection that is provisioned (typically not a problem for me because I do not update content types globally often). However, I know others in the community have produced PowerShell scripts to making updates to Content Types across the farm when additions need to be made.

**Comment by pdemro** [comment]
Thanks @bcameron1231 !  This approach could work for an organization which embraces provisioning governance for their Office 365 entities like Teams and SharePoint sites.  

One major benefit of the Content Type Hub is how it will provision the content types to sites/teams which are created via out-of-box provisioning mechanisms (in addition to the PnP provisioning process)

I opened another user voice on the subject of manually triggering Content Type Hub syndication framing it in terms of the Graph API instead of CSOM - https://sharepoint.uservoice.com/forums/329220-sharepoint-dev-platform/suggestions/40481089-allow-publishing-of-content-type-hub-content-types

**Comment by bcameron1231** [comment]
Completely agree, I wish we had more control over the syndication process in SharePoint Online.

If you are looking to provision Content Types and such when creating new sites, have you had a look into using Site Designs and Site Scripts? You can use them to provision on newly created sites, or you can augment them to run PnP Templates on every new site creation from the out of the box User Experience. 

I wish I had better recommendations for you, unfortunately I too feel this pain! :)

**Comment by bcameron1231** [comment]
@pdemro  Hope you don't mind, I am going to close this ticket. Not sure there is much more guidance that can be provided. Always here if you have any further questions!

**Comment by pdemro** [comment]
No problem @bcameron1231 thank you for the thoughtful discussion
