### ISSUE TITLE
Personal Calendar and Personal Tasks Web Parts do not work together on the same page. 

### ISSUE THREAD

**Issue by iorivera** [pnp/sp-starter-kit#503]
I installed both of the web parts to the tenant app catalog. Along with the Library-Shared starter kit.  I continue to experience the same error message mentioned in this bug
https://github.com/microsoftgraph/microsoft-graph-toolkit/issues/794.

I have built and packaged the web parts and the issue will also persist. I am not sure what other steps to follow. Does any one have any suggestions on this. Let me know what other information I can provide

**Comment by bcameron1231** [comment]
Hi, correct we are aware of this. As you mention this is due to the Microsoft Graph Tool Kit. This has been fixed in MGT, but we have yet to upgrade all of the web parts that use it. This is on the list, and thank you for reporting

**Comment by eoverfield** [comment]
This has been updated in the latest release of the starter kit. You will want to refresh your master branch and re-deploy the starterkit.pnp template. Or you could just grab the latest sppkg's for these two webparts and update those in your app catalog. Be aware that if you follow this route, you will also need to install the new mgt-spfx required sppkg, found in ./source/mgt-spfx.

Generally this issue was addressed by upgrades to mgt version 2.2.1.
