### ISSUE TITLE
Banner web part

### ISSUE THREAD

**Issue by tommrihu** [pnp/sp-starter-kit#672]
Hi
 Installed Banner web part witout any problem ,but  cant se the webpart in the site, 

thankful for help
regards
Tommy

**Comment by robertcaretta** [comment]
I concur. Why is this webpart hidden by default. If you deploy the spfx-starter-kit you will have to rebuild the webpart and redeploy it separately. Makes no sense.

**Comment by eoverfield** [comment]
Generally this was hidden for a few reasons. First was because there is a first party webpart within SharePoint that does that same thing. That being the Image webpart. Second, instead of simply removing the webpart, we saw this as another technology demonstrator on how SPFx components may be added, yet hidden by default, such that they could then be added to aspects of SharePoint via code.

https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/ProtectAnAPI/appId/b46954c9-2f80-47ba-bb38-b8d3168a0312
